#=====================================================================================================
# Script Name: FallSalmonSurvey2020-017.R
# Modified from TowPlots.R in GearComparison2018-10 project and FranklinTestin2020-03.R
#
# compare and graph net opening, warp out and door spread
#   for footrope & headrope RBR readings from each tow
#
# R Version: 3.6.1
# Script Author: Ben Snow
# Script Date: Aug 22, 2018
# Update: Sept 2018 by Erika Anderson for manual events instead of GFBio
# Update: Modified script to produce plots to include in tech report 2018-12-11
# Update: Modified script to produce plots for Franklin fishing trials (cancelled sue to covid)
# Update: Modified for fall juvenile salmon survey 2020-017 Oct 6-16, 2020
#
# Make sure RBR sensors are synced before deployment 
# use local time to match bridge log
#=====================================================================================================
#Required packages#

require(tidyverse) # data wrangling 
require(readxl) # excel files
require(lubridate) # dates
require(data.table) # manipulate data faster
library(stringr) # string manipulation
library(here) # relative file paths

########################################################################

# folder with survey data
dataFolder <- here::here("Input/2020-017_FallSalmonSurvey")

# folder for figures produced
figFolderName <- paste0(getwd(), "/Output/Figures", Sys.Date())

# create folder if it doesn't exist
dir.create(figFolderName)

# folder for data produced
dataFolderName <- paste0(getwd(), "/Output/Data", Sys.Date())

# create folder if it doesn't exist
dir.create(dataFolderName)

Event_input <- here::here("Input/2020-017_FallSalmonSurvey/2020-017_BridgeLog_digital-2020-09-16.xlsx")
Headrope_input <- paste0(dataFolder, "/HEADROPE")
Footrope_input <- paste0(dataFolder, "/FOOTROPE")


######################################################################################################

# Read in Manual Fishing Event from excel file including:
# Station_ID, Event #, Location, Date, Start Time, End Time, tow_time, 
# Net OPenning, Head Depth, Warp, Comments
event_num <- read_xlsx(Event_input)
event_num <- subset(event_num, select = c("StationID", "Event", "Type", "Location", "Year", "Month", "Day", 
                                          "StartTime", "StopTime", "TowTime", "VerticalNetOpening", 
                                          "TargetHeadDepth", "ActualHeadDepth", "Warp", "Comments"))


# strip incorrect dates that were autogenerated on load from excel
event_num$StartTime <- str_sub(event_num$StartTime, 11, -1)
event_num$StopTime <- str_sub(event_num$StopTime, 11, -1)
event_num$TowTime <- str_sub(event_num$TowTime, 11, -1)

# select trawl events only
event_num <- event_num %>%
  mutate(Type_simp = toupper(str_extract_all(Type, "Trawl"))) %>%
  filter(Type_simp == "TRAWL")

# make date time columns for start and stop using GF_Bio columns names
event_num <- event_num %>%
  mutate(FE_END_DEPLOYMENT_TIME = ymd_hms(paste0(Year, "-", Month, "-", Day, "-", StartTime)),
         FE_BEGIN_RETRIEVAL_TIME = ymd_hms(paste0(Year, "-", Month, "-", Day, "-", StopTime))) %>%
  rename(FE_MAJOR_ID = Event, 
         TRLSP_WARP_LENGTH = Warp)

# assign timezone to Pacific from default UTC
# assuming that devices and bridge log are in Pacific time
event_num$FE_END_DEPLOYMENT_TIME <- force_tz(event_num$FE_END_DEPLOYMENT_TIME, tzone = "CANADA/PACIFIC"  )
event_num$FE_BEGIN_RETRIEVAL_TIME <- force_tz(event_num$FE_BEGIN_RETRIEVAL_TIME, tzone = "CANADA/PACIFIC")

# plot events to compare to depth sensors depths as QC
ggplot(data = event_num, aes(x = StartTime, y = TowTime)) +
  geom_bar(stat = "identity") +
  labs(x = "Start Time") +
  theme_bw() +
  facet_wrap(~Day)

# Read in excel file exports from RBR duet loggers on headrope and footrope; loop through all .xlsx files in the headrope and
# footrope directories, and merge them into one file for each of the footrop end headrope datasets.
merged_foot <- data.frame()
merged_head <- data.frame()

# load all headrope files
head_files <- list.files(path = Headrope_input, pattern = ".xlsx")

for (i in 1:length(head_files))
{
  name <- as.character(i)
  assign(name, read_xlsx(path = paste0(Headrope_input, "/", head_files[i]), sheet = 3, skip = 1))
  if (name == "1")
  {merged_head <- get(name)
  }else merged_head <- rbind(merged_head, get(name))
  rm(list = c(i))
}

# load foot rope files
foot_files <- list.files(path = Footrope_input, pattern = ".xlsx")

for (k in 1:length(foot_files))
{
  name <- as.character(k)
  assign(name, read_xlsx(path = paste0(Footrope_input, "/", foot_files[k]), sheet = 3, skip = 1))
  if (name == "1")
  {merged_foot <- get(name)
  }else merged_foot <- rbind(merged_foot, get(name))
  rm(list = c(k))
}

# Match foot and headrope record times, merge them into a new data frame with both foot and headrope depth readings.
net_calcs <- merge(merged_foot, merged_head, by.x = 'Time', by.y = "Time", suffixes = c('_foot','_head'))

#Keep only Time, and foot and headrope depth columns
net_calcs <- subset(net_calcs, select = c("Time","Depth_foot", "Depth_head"))

# Clip RBR data to readings where the foot rope and head rope are greater than 0 m deep.
net_calcs <- filter(net_calcs, Depth_foot > 0)
net_calcs <- filter(net_calcs, Depth_head > 0)

#assign RBR data to local time for graphing and comparison with bridge log
net_calcs$Time <- force_tz(net_calcs$Time, tzone = "Canada/Pacific")

# # expand event interval to show deployment and retrieval on graph
 minute(event_num$FE_END_DEPLOYMENT_TIME) <- minute(event_num$FE_END_DEPLOYMENT_TIME)  - 10
 minute(event_num$FE_BEGIN_RETRIEVAL_TIME) <- minute(event_num$FE_BEGIN_RETRIEVAL_TIME)  + 10

#Search the set intervals in the event_num dataframe, 
#(i.e. time between FE_END_DEPLOYMENT_TIME and FE_BEGIN_RETRIEVAL_TIME, for each event)
#and match the timestamp of each RBR reading to the correct intervals in the net_calcs dataframe.

# Create vector of RBR timestamps
rbr_times <- net_calcs$Time

#Coerce to a event_num to a data.table object, then search within intervals.
plotting_DF <- setDT(event_num)[data.table(rbr_times), on = .(FE_END_DEPLOYMENT_TIME <= rbr_times, FE_BEGIN_RETRIEVAL_TIME >= rbr_times)]

#Remove unused columns, and rename for ease of merging.
plotting_DF <- subset(plotting_DF, select = c("FE_MAJOR_ID", "VerticalNetOpening", "TargetHeadDepth", "TRLSP_WARP_LENGTH",
                                              "Comments", "FE_END_DEPLOYMENT_TIME", "FE_BEGIN_RETRIEVAL_TIME"))
colnames(plotting_DF) <- c("Event","VerticalNet", "TargetHead", "Warp", "Comment", "StartTime", "StopTime")

#Merge the plotting_DF and net_calcs data frames using a common time stampvalue.
plotting_DF <- merge(plotting_DF, net_calcs, by.x = "StartTime", by.y = "Time")

#Filter out and Events that are NA (outside the trawl set periods)
plotting_DF <- filter(plotting_DF, !is.na(Event))

#Calculate net opening (footrope - headrope)
plotting_DF$Opening <- plotting_DF$Depth_foot - plotting_DF$Depth_head

#Plot each Event  

for (j in unique(plotting_DF$Event))
{
  opening_data <- filter(plotting_DF, Event == j)
  netdetails <- paste("Target Headrope Depth: ", as.character(opening_data$TargetHead), "m", "\n",
                      "Mean RBR vertical net opening:",as.character(round(mean(opening_data$Opening),1)), "m", "\n",
                      "Vessel vertical net opening: ", as.character(opening_data$VerticalNet), "m", "\n",
                      "Warp Out: ", as.character(opening_data$Warp), "m", sep = " ")
                      
  
  ggplot(opening_data) + 
    geom_line(aes(x = StartTime, y = Depth_head)) + 
    geom_line(aes(x = StartTime, y = Depth_foot)) +
    scale_x_datetime(date_labels = "%b-%d %H:%M") +
    scale_y_reverse(lim = c(60,0)) +
    labs(y = "Depth (m)", 
         x = "Date & Time",
         title = paste("Event", j, sep = " "),
         subtitle = netdetails) +
    theme_bw() +
    geom_hline(yintercept = 15, linetype = "dashed")
  
  ggsave(filename = str_c(figFolderName, "/NetPlot", as.character(j), ".png"))
}

# summarize data 
plotting_DF_sum <- plotting_DF %>%
  group_by(Event, TargetHead, Warp, Comment, VerticalNet) %>%
  summarise(RbrVerticalNet = round(mean(Opening), 1), .groups = "drop") %>%
  ungroup()

# save to pull into stats Rscript
write.csv(plotting_DF_sum, 
          str_c(dataFolderName, "/RBROpenings", Sys.Date(), ".csv", sep = ""), 
          row.names = FALSE)


